name: Javadoc Generation
on:
  push:
    branches:
      - "master"
      - "testing-*"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        run: |
          cd ~/
          sudo apt list --installed
          sudo apt --purge remove -y adoptopenjdk-8 adoptopenjdk-11
          wget -O java.tar.gz --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
          sudo mkdir /usr/lib/jvm
          cd /usr/lib/jvm
          sudo tar -xvzf ~/java.tar.gz
          sudo sed -i '$ s/.$/:/usr/lib/jvm/jdk-17/bin"/' /etc/environment
          sudo echo -e "JAVA_HOME="/usr/lib/jvm/jdk-17"" >> /etc/environment
          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-17/bin/java" 0
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk-17/bin/javac" 0
          sudo update-alternatives --install "/usr/bin/javadoc" "javadoc" "/usr/lib/jvm/jdk-17/bin/javadoc" 0
          sudo update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/jdk-17/bin/javac
          sudo update-alternatives --set javadoc /usr/lib/jvm/jdk-17/bin/javadoc
          update-alternatives --list java
          update-alternatives --list javac
          update-alternatives --list javadoc

      - name: Debug Workspace
        run: |
          exec bash
          echo -e "DEBUG LOGS START\n\n\n"
          ./gradlew --version
          echo -e "\n\n\n\n\n------------------------------------------------------------------------------------------\n\n\n\n\n"
          echo -e "Tree:\n"
          find .
          echo -e "\n\n"
          update-alternatives --list java
          update-alternatives --list javac
          update-alternatives --list javadoc
          java --version
          echo -e "\n\n\nDEBUG LOGS END"
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Setup Javadoc Source
        run: |
          rm -rf javadoc-output
          rm -rf javadoc-workspace
          rm -rf javadoc-temp-workspace
          mkdir javadoc-output
          mkdir javadoc-workspace
          mkdir javadoc-temp-workspace
          rm -rf ./TeamCode/build/
          rm -rf ./FtcRobotController/build/
          cp -r -p ./TeamCode/ ./javadoc-workspace/
          cp -r -p ./FtcRobotController/ ./javadoc-workspace/
          cp -r -p ~/.gradle/caches/modules-2/files-2.1/ ./javadoc-temp-workspace/
          mv ./javadoc-temp-workspace/files-2.1/ ./javadoc-workspace/files-final/ 
          echo -e "DEBUG LOGS START\n\n\n"
          find ./javadoc-workspace/
          echo -e "\n\n\nDEBUG LOGS END"
#      - name: Install Android Studio
#        run: |
#          cp -r -p jdtar/android-studio.tar.gz ./
#          tar -xf android-studio.tar.gz
      - name: Generate Javadoc
        run: |
          sudo snap install android-studio --classic
          /snap/android-studio/current/android-studio/jre/bin/javadoc -Xdoclint:none -public -splitindex -use -author -version -sourcepath $ANDROID_HOME/platforms/android-29/android.jar -d ./javadoc-output -link https://docs.oracle.com/en/java/javase/11/docs/api/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/ftccommon/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/hardware/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/inspection/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/onbotjava/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/robotcore/package-list $(find ./javadoc-workspace/ -name "*.java" -not -type d) --ignore-source-errors
#      - name: Generate Javadoc
#        run: |
#          cd android-studio/jre/bin
#         ./javadoc -d ./javadoc-output $(find ../../ -name "*.java") -public -splitindex -use -author -version -Xdoclint:none --ignore-source-errors -link https://docs.oracle.com/en/java/javase/11/docs/api/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/ftccommon/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/hardware/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/inspection/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/onbotjava/ -link https://xaverianteamrobotics.github.io/FtcRobotController/javadocs/libs/robotcore/
      - name: Find
        run: find .
      - name: Upload the Javadoc output
        uses: actions/upload-artifact@v2
        with:
          name: Javadoc-output
          path: ./javadoc-output/

      - name: Commit and push the new Javadoc folder
        run: |
          # Set up Git and environment variables
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          shopt -s dotglob
          export BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")

          # Move Javadoc output and build reports
          mv javadoc-output/ ..
          mkdir ../team-reports/
          mv ./TeamCode/build/reports/*  ../team-reports/
          mkdir ../sdk-reports/
          mv ./FtcRobotController/build/reports/* ../sdk-reports/

          # Checkout gh-pages branch
          git reset --hard HEAD
          git clean -f -d -x
          git remote set-branches origin --add 'gh-pages'
          git fetch -a -v
          git checkout gh-pages

          # Copy Javadoc docs to gh-pages
          rm -rf ./javadocs/${BRANCH_NAME}/ || true
          mkdir -p ./javadocs/${BRANCH_NAME}/
          mv ../javadoc-output/* ./javadocs/${BRANCH_NAME}/

          # Copy build reports to gh-pages
          rm -rf ./reports/${BRANCH_NAME}/ || true
          mkdir -p ./reports/${BRANCH_NAME}/team-reports/
          mkdir -p ./reports/${BRANCH_NAME}/sdk-reports/
          mv ../team-reports/* ./reports/${BRANCH_NAME}/team-reports/
          mv ../sdk-reports/* ./reports/${BRANCH_NAME}/sdk-reports/
          mv ./reports/${BRANCH_NAME}/team-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/team-reports/index.html || true
          mv ./reports/${BRANCH_NAME}/sdk-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/sdk-reports/index.html || true

          # Commit and push changes
          git add -A
          git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)

          Information:
            Repository: $GITHUB_REPOSITORY
            Branch: $GITHUB_REF
            Commit: $GITHUB_SHA
            Who triggered action: $GITHUB_ACTOR"
          git push
