name: Javadoc Generation
on:
  push:
    branches: [master, testing-Thomas-Ricci, testing-Michael-Lachut, testing-Donald-Hicks, testing-Colin-Teahan]
  workflow_dispatch:

jobs:
  master:
    runs-on: ubuntu-latest
    env:
      NAME_OF_BRANCH: master

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: $env.NAME_OF_BRANCH

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: gradle

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Generate documentation with Javadoc
      run: javadoc -d javadoc-output $(find . -name "*.java") -Xdoclint:none --ignore-source-errors

    - name: Upload the Javadoc output
      uses: actions/upload-artifact@v2
      with:
        name: Javadoc-output
        path: ./javadoc-output/

    - name: Commit and push new Javadoc folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        mv javadoc-output/ ..
        mv ./TeamCode/build/reports/  ..
        mkdir ../sdk-reports/
        mv ./FtcRobotController/build/reports/* ../sdk-reports/
        git remote set-branches origin '*'
        git fetch -v
        git checkout gh-pages
        rm -rf javadocs/ || true
        mv ../javadoc-output/ ./javadocs/$env.NAME_OF_BRANCH
        rm -rf reports/ || true
        mv ../reports/ .
        mv ../sdk-reports/ ./reports/sdk-reports/$env.NAME_OF_BRANCH
        git add .
        git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
          Repository: $GITHUB_REPOSITORY
          Branch: $GITHUB_REF
          Commit: $GITHUB_SHA
          Who triggered action: $GITHUB_ACTOR"
        git push

  testing-Thomas-Ricci:
    runs-on: ubuntu-latest
    env:
      NAME_OF_BRANCH: testing-Thomas-Ricci
    needs: [master]
    if: always()

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: $env.NAME_OF_BRANCH

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: gradle

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Generate documentation with Javadoc
      run: javadoc -d javadoc-output $(find . -name "*.java") -Xdoclint:none --ignore-source-errors

    - name: Upload the Javadoc output
      uses: actions/upload-artifact@v2
      with:
        name: Javadoc-output
        path: ./javadoc-output/

    - name: Commit and push new Javadoc folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        mv javadoc-output/ ..
        mv ./TeamCode/build/reports/  ..
        mkdir ../sdk-reports/
        mv ./FtcRobotController/build/reports/* ../sdk-reports/
        git remote set-branches origin '*'
        git fetch -v
        git checkout gh-pages
        rm -rf javadocs/ || true
        mv ../javadoc-output/ ./javadocs/$env.NAME_OF_BRANCH
        rm -rf reports/ || true
        mv ../reports/ .
        mv ../sdk-reports/ ./reports/sdk-reports/$env.NAME_OF_BRANCH
        git add .
        git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
          Repository: $GITHUB_REPOSITORY
          Branch: $GITHUB_REF
          Commit: $GITHUB_SHA
          Who triggered action: $GITHUB_ACTOR"
        git push

  testing-Michael-Lachut:
    runs-on: ubuntu-latest
    env:
      NAME_OF_BRANCH: testing-Michael-Lachut
    needs: [master, testing-Thomas-Ricci]
    if: always()

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: $env.NAME_OF_BRANCH

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: gradle

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Generate documentation with Javadoc
      run: javadoc -d javadoc-output $(find . -name "*.java") -Xdoclint:none --ignore-source-errors

    - name: Upload the Javadoc output
      uses: actions/upload-artifact@v2
      with:
        name: Javadoc-output
        path: ./javadoc-output/

    - name: Commit and push new Javadoc folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        mv javadoc-output/ ..
        mv ./TeamCode/build/reports/  ..
        mkdir ../sdk-reports/
        mv ./FtcRobotController/build/reports/* ../sdk-reports/
        git remote set-branches origin '*'
        git fetch -v
        git checkout gh-pages
        rm -rf javadocs/ || true
        mv ../javadoc-output/ ./javadocs/$env.NAME_OF_BRANCH
        rm -rf reports/ || true
        mv ../reports/ .
        mv ../sdk-reports/ ./reports/sdk-reports/$env.NAME_OF_BRANCH
        git add .
        git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
          Repository: $GITHUB_REPOSITORY
          Branch: $GITHUB_REF
          Commit: $GITHUB_SHA
          Who triggered action: $GITHUB_ACTOR"
        git push

  testing-Donald-Hicks:
    runs-on: ubuntu-latest
    env:
      NAME_OF_BRANCH: testing-Donald-Hicks
    needs: [master, testing-Thomas-Ricci, testing-Michael-Lachut]
    if: always()

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: $env.NAME_OF_BRANCH

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: gradle

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Generate documentation with Javadoc
      run: javadoc -d javadoc-output $(find . -name "*.java") -Xdoclint:none --ignore-source-errors

    - name: Upload the Javadoc output
      uses: actions/upload-artifact@v2
      with:
        name: Javadoc-output
        path: ./javadoc-output/

    - name: Commit and push new Javadoc folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        mv javadoc-output/ ..
        mv ./TeamCode/build/reports/  ..
        mkdir ../sdk-reports/
        mv ./FtcRobotController/build/reports/* ../sdk-reports/
        git remote set-branches origin '*'
        git fetch -v
        git checkout gh-pages
        rm -rf javadocs/ || true
        mv ../javadoc-output/ ./javadocs/$env.NAME_OF_BRANCH
        rm -rf reports/ || true
        mv ../reports/ .
        mv ../sdk-reports/ ./reports/sdk-reports/$env.NAME_OF_BRANCH
        git add .
        git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
          Repository: $GITHUB_REPOSITORY
          Branch: $GITHUB_REF
          Commit: $GITHUB_SHA
          Who triggered action: $GITHUB_ACTOR"
        git push

  testing-Colin-Teahan:
    runs-on: ubuntu-latest
    env:
      NAME_OF_BRANCH: testing-Colin-Teahan
    needs: [master, testing-Thomas-Ricci, testing-Michael-Lachut, testing-Donald-Hicks]
    if: always()

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: $env.NAME_OF_BRANCH

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: gradle

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Generate documentation with Javadoc
      run: javadoc -d javadoc-output $(find . -name "*.java") -Xdoclint:none --ignore-source-errors

    - name: Upload the Javadoc output
      uses: actions/upload-artifact@v2
      with:
        name: Javadoc-output
        path: ./javadoc-output/

    - name: Commit and push new Javadoc folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        mv javadoc-output/ ..
        mv ./TeamCode/build/reports/  ..
        mkdir ../sdk-reports/
        mv ./FtcRobotController/build/reports/* ../sdk-reports/
        git remote set-branches origin '*'
        git fetch -v
        git checkout gh-pages
        rm -rf javadocs/ || true
        mv ../javadoc-output/ ./javadocs/$env.NAME_OF_BRANCH
        rm -rf reports/ || true
        mv ../reports/ .
        mv ../sdk-reports/ ./reports/sdk-reports/$env.NAME_OF_BRANCH
        git add .
        git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
          Information:
          Repository: $GITHUB_REPOSITORY
          Branch: $GITHUB_REF
          Commit: $GITHUB_SHA
          Who triggered action: $GITHUB_ACTOR"
        git push
